### ISSUE TITLE
Allow Lights to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [polyvalord/extlights#1]
Forge v28.1.44
Extended Lights v1.6

Currently, the lamps and other lights cannot be waterlogged. Allowing this would add more immersion to the game for underwater exploration.
![2019-10-12_01 21 29](https://user-images.githubusercontent.com/12000593/66696298-637b9500-ec90-11e9-994e-b936098c2916.png)

**Comment by polyvalord** [comment]
I will do it as soon as possible !

**Comment by polyvalord** [comment]
It's done for all the modern lights and neons
